#!/bin/sh

export PATH=./node_modules/.bin:$PATH

./css_mixins/konnun.sh
./css_mixins/reports.sh
./css_mixins/ops.sh
./css_mixins/pdfs.sh
./css_mixins/crm.sh
./css_mixins/charts.sh

echo "Compiled 6 .css files"


cat js/lib/jquery.1.11.3.min.js js/global/messages.js js/lib/soundmanager/soundmanager2-nodebug-jsmin.js js/lib/clipboard.js js/konnun.js | jsmin > js/konnun-min.js

cat js/lib/jquery.1.11.3.min.js js/global/messages.js js/lib/papa-parse.js js/lib/sort-table.js js/lib/jsdifflib/difflib.js js/lib/jsdifflib/diffview.js js/ops.js | jsmin > js/ops-min.js

#cat js/lib/bean.js js/lib/jquery-3.6.0.min.js js/lib/enquire.js js/global/messages.js js/lib/sort-table.js js/reports.js | jsmin > js/reports-min.js
cat js/lib/bean.js js/lib/jquery.1.11.3.min.js js/lib/enquire.js js/global/messages.js js/lib/sort-table.js js/reports.js | jsmin > js/reports-min.js

cat js/lib/bean.js js/lib/jquery.1.11.3.js js/lib/enquire.js js/global/messages.js js/lib/sort-table.js js/reports.js > js/reports-debug.js

cat js/lib/jquery.1.11.3.min.js js/lib/enquire.js js/lib/html5shiv.js js/visar.js | jsmin > js/visar-min.js

cat js/lib/jquery.1.11.3.min.js js/lib/html5shiv.js js/global/messages.js js/lib/sort-table.js js/lib/papa-parse.js | jsmin > js/crm-min.js

echo "Compiled 4 .js files"
