#!/bin/sh

lessc -x less/konnun.less css/konnun.css
lessc -x less/reports.less css/reports.css
lessc -x less/visar.less css/visar.css
lessc -x less/ops.less css/ops.css

echo "Compiled 4 .less files"


cat js/lib/jquery.1.9.1.min.js js/global/messages.js js/konnun.js | jsmin > js/konnun-min.js

cat js/lib/jquery.1.9.1.min.js js/global/messages.js js/ops.js | jsmin > js/ops-min.js

cat js/lib/jquery.1.9.1.min.js js/lib/enquire.js js/global/messages.js js/reports.js | jsmin > js/reports-min.js

echo "Compiled 3 .js files"
